WWW-Ministries-Project/Frontend

package-lock.json
package.json
src/axiosInstance.js
src/main.jsx
src/pages/Authentication/pages/LoginPage/LoginPage.jsx
src/pages/HomePage/Components/Header.jsx
src/pages/HomePage/Components/reusable/NotificationFlag.jsx
src/pages/HomePage/Components/reusable/SelectField.jsx
src/pages/HomePage/Components/reusable/TableComponentOld.jsx
src/pages/HomePage/HomePage.jsx
src/pages/HomePage/pages/DashBoard/DashBoard.jsx
src/pages/HomePage/pages/Settings/Settings.jsx
src/utils/helperFunctions.js

Decoding token
- [ x] Tests have been added to all functions
- [ x] Documentation has been updated
- [ x] Changes follow coding standards

decoding token

---

.github/workflows/prevent-branch-reuse.yml

test for github action prevent code reusseable

---

src/pages/Authentication/pages/LoginPage/LoginPage.jsx

removed unused import

---

.github/workflows/prevent-branch-reuse.yml

Reuseable branches

---

jsconfig.json
src/appRoutes.js
src/components/ToggleInput.jsx
src/pages/HomePage/HomePage.jsx
src/pages/HomePage/pages/Settings/Components/AccessForm.jsx
src/pages/HomePage/pages/Settings/Components/FormsComponent.jsx
src/pages/HomePage/pages/Settings/Settings.jsx
src/utils/helperFunctions.js

Authorization

---

src/index.css
src/main.jsx
src/pages/HomePage/HomePage.jsx
src/pages/HomePage/pages/AssetsManagement/AssetManagement.jsx
src/pages/HomePage/pages/AssetsManagement/utils/utils.jsx

Asset management

---

src/components/ToggleInput.jsx
src/pages/Authentication/utils/helpers.js
src/pages/HomePage/pages/Settings/Components/AccessForm.jsx
src/pages/HomePage/pages/Settings/Settings.jsx
src/pages/HomePage/pages/Settings/utils/helperFunctions.jsx

Access level

---

src/pages/HomePage/pages/Settings/Components/AccessForm.jsx
src/pages/HomePage/pages/Settings/Settings.jsx

hidding and showing access block

---

src/components/SearchMembersCard.jsx

Add search members card component

---

src/pages/HomePage/pages/AssetsManagement/AssetManagement.jsx

edit assets

---

src/assets/ellipse.svg
src/axiosInstance.js
src/pages/Authentication/pages/LoginPage/LoginPage.jsx
src/pages/HomePage/Components/reusable/TableComponent.jsx
src/pages/HomePage/pages/Members/Components/MemberCard.jsx
src/pages/HomePage/pages/Members/Members.jsx

member card

---

src/pages/HomePage/pages/Members/Members.jsx

table switch

---

src/pages/EventsManagement/Components/EventsCard.jsx
src/pages/EventsManagement/EventsManagement.jsx

route for viewing events

---

src/index.css
src/pages/EventsManagement/Components/MemberConfirmation.jsx
src/pages/EventsManagement/Components/MemberConfirmed.jsx
src/pages/EventsManagement/Components/RegisterMember.jsx
src/pages/EventsManagement/Components/SearchMember.jsx
src/pages/EventsManagement/pages/EventRegister.jsx
src/pages/EventsManagement/pages/ViewEvents.jsx
src/routes/appRoutes.jsx

api calls to create attendance for event

---

src/pages/EventsManagement/pages/EventRegister.jsx
src/pages/EventsManagement/pages/ViewEvents.jsx
src/pages/EventsManagement/utils/eventHelpers.js

event attendees

---

package-lock.json
package.json
src/auth/AuthWrapper.jsx
src/store/userStore.ts

initialization of store

---

src/utils/helperFunctions.js

fixed firstLetter functioin

---

src/index.css
src/pages/EventsManagement/EventsManagement.jsx
src/pages/EventsManagement/pages/CreateEvent.jsx
src/pages/HomePage/Components/Header.jsx
src/pages/HomePage/HomePage.jsx
src/pages/HomePage/pages/AssetsManagement/AssetManagement.jsx
src/pages/HomePage/pages/DashBoard/DashBoard.jsx
src/pages/HomePage/pages/Members/Members.jsx
src/pages/HomePage/pages/Members/pages/AddMember.tsx
tailwind.config.js

Top level styling

---

src/components/AddSignature.tsx
src/components/ImageUpload.jsx
src/components/Modal.tsx
src/hooks/useFileUpload.ts
src/pages/HomePage/pages/AssetsManagement/AssetManagement.jsx
src/pages/HomePage/pages/DashBoard/DashBoard.jsx
src/pages/HomePage/pages/EventsManagement/pages/CreateEvent.jsx

feat: add file upload hook

---

src/components/AddSignature.tsx
src/components/ImageUpload.jsx
src/components/Modal.tsx
src/hooks/useFileUpload.ts
src/pages/HomePage/pages/EventsManagement/pages/CreateEvent.jsx

feat: add signature modal

---

src/pages/HomePage/Components/NavigationLink.tsx
src/pages/HomePage/Components/SideBar.jsx
src/pages/HomePage/Components/SidebarSubmenu.tsx
src/routes/appRoutes.jsx

feat: add sub-routes

---

src/pages/HomePage/Components/SideBar.jsx
src/pages/HomePage/Components/SidebarSubmenu.tsx
src/routes/appRoutes.jsx

Sub routes

---

src/pages/HomePage/Components/Header.jsx
src/pages/HomePage/Components/SideBarMobile.jsx
src/pages/HomePage/HomePage.jsx

feat: add responsive sidebar

---

src/CustomHooks/useFetch.tsx
src/CustomHooks/usePost.tsx
src/pages/HomePage/pages/Members/Members.tsx
src/pages/HomePage/pages/Members/pages/AddMember.tsx
src/pages/HomePage/pages/Members/utils/apiCalls.ts
src/pages/HomePage/pages/Members/utils/membersInterfaces.ts
src/pages/HomePage/utils/helperFunctions.jsx
src/utils/apiCalls.ts
src/utils/helperFunctions.ts
src/utils/interfaces.ts

delete members in table mode

---

src/pages/HomePage/pages/Members/utils/membersInterfaces.ts
src/pages/HomePage/pages/Members/utils/tableColums.tsx

type corrections

---

src/components/AddSignature.tsx
src/pages/HomePage/pages/Requisitions/hooks/useAddRequisition.ts
src/pages/HomePage/pages/Requisitions/pages/Request.tsx
src/pages/HomePage/pages/Requisitions/utils/requisitionSchema.ts

feat: signing on making request

---

src/pages/HomePage/pages/Requisitions/components/EditableTable.tsx
src/pages/HomePage/pages/Requisitions/pages/RequestDetails.tsx
src/pages/HomePage/utils/stringOperations.ts

refactor: editable

---

src/pages/HomePage/pages/Requisitions/pages/Request.tsx
src/pages/HomePage/pages/Requisitions/types/requestInterface.ts

fix: program id

---

src/pages/HomePage/pages/Requisitions/utils/requisitionSchema.ts

request comment

---

src/Wrappers/SubFormWrapper.tsx
src/assets/AngleRight.jsx
src/components/ContactInput.tsx
src/pages/HomePage/Components/BreadCrumb.tsx
src/pages/HomePage/Components/subforms/ContactDetails.tsx
src/pages/HomePage/Components/subforms/PersonalDetails.tsx
src/pages/HomePage/pages/EventsManagement/Components/RegisterMember.tsx
src/pages/HomePage/pages/EventsManagement/Components/SearchMember.jsx
src/pages/HomePage/pages/Members/Components/MembersForm.tsx
src/pages/HomePage/pages/Members/Components/RadioInput.tsx
src/pages/HomePage/pages/Members/Components/subforms/WorkInfoSubForm.tsx
src/pages/HomePage/pages/Members/pages/AddMember.tsx
src/pages/HomePage/pages/Members/pages/MemberInformation.tsx

adding members

---

src/components/ContactInput.tsx
src/components/subform/ChildrenSubForm.tsx
src/components/subform/ContactsSubForm.tsx
src/components/subform/EmergencyContact.tsx
src/components/subform/PersonalDetails.tsx
src/components/subform/UserSubForm.tsx
src/components/subform/WorkInfoSubForm.tsx
src/pages/Authentication/components/AuthenticationForm.jsx
src/pages/HomePage/Components/reusable/InputDiv.tsx
src/pages/HomePage/pages/Members/Components/MembersForm.tsx
src/pages/Registration/Registration.tsx

Registration

---

src/components/fields/CountryField.tsx
src/components/subform/ContactsSubForm.tsx
src/components/subform/PersonalDetails.tsx
src/pages/Registration/Registration.tsx

countryField

---

src/pages/HomePage/pages/VisitorManagement/Components/VisitorForm.tsx

renameed event component

---

src/pages/HomePage/pages/Members/Members.tsx
src/pages/HomePage/pages/Members/pages/ManageMember.tsx
src/routes/appRoutes.jsx
src/utils/api/apiFunctions.ts

api typescript

---

src/pages/HomePage/HomePage.tsx
src/pages/HomePage/pages/DashBoard/DashBoard.tsx

stats uncommented

---

src/utils/api/apiFetch.ts

grouped api calls

---

src/CustomHooks/usePut.tsx
src/pages/HomePage/pages/Members/pages/ManageMember.tsx
src/pages/HomePage/pages/VisitorManagement/Components/VisitorForm.tsx
src/pages/HomePage/pages/VisitorManagement/VisitorManagement.tsx
src/utils/api/apiConstructor.ts
src/utils/api/apiFunctions.ts
src/utils/api/apiPut.ts
src/utils/interfaces.ts

Visitor management

---

.husky/pre-commit
src/components/ContactInput.tsx
src/components/subform/ContactsSubForm.tsx
src/pages/HomePage/pages/Members/Components/MembersForm.tsx

error messages are being shown

---

src/utils/api/apiConstructor.ts
src/utils/api/apiFunctions.ts
src/utils/api/apiPut.ts
src/utils/interfaces.ts

api typescript correction starting from put

---

src/pages/HomePage/pages/AssetsManagement/utils/utils.tsx
src/pages/HomePage/pages/VisitorManagement/Components/FollowUpForm.tsx
src/pages/HomePage/pages/VisitorManagement/Components/FollowUps.tsx
src/pages/HomePage/pages/VisitorManagement/pages/FollowUps.tsx
src/pages/HomePage/pages/VisitorManagement/pages/VisitorDetails.tsx
src/utils/api/apiDelete.ts
src/utils/api/apiPost.ts
src/utils/api/apiPut.ts
src/utils/api/visitors/interfaces.ts
src/utils/interfaces.ts

follow up form

---

src/components/HeaderControls.tsx
src/pages/HomePage/Components/PageOutline.tsx
src/pages/HomePage/pages/AssetsManagement/AssetManagement.tsx
src/pages/HomePage/pages/DashBoard/DashboardPage.tsx
src/pages/HomePage/pages/DashBoard/pages/Overview.tsx
src/pages/HomePage/pages/EventsManagement/EventsManagement.tsx
src/pages/HomePage/pages/Members/Members.tsx
src/pages/HomePage/pages/MinistrySchool/MinistrySchool.tsx
src/pages/HomePage/pages/Users/UserManagement.tsx
src/pages/HomePage/pages/VisitorManagement/Components/FollowUps.tsx
src/pages/HomePage/pages/VisitorManagement/Components/Visit.tsx
src/pages/HomePage/pages/VisitorManagement/VisitorManagement.tsx
src/pages/HomePage/pages/VisitorManagement/pages/VisitorDetails.tsx
src/pages/HomePage/utils/helperFunctions.ts

Refactor header

---

src/CustomHooks/useFetch.tsx
src/components/Dialog.tsx
src/components/NotificationCard.tsx
src/pages/HomePage/Components/reusable/LoaderComponent.tsx
src/pages/HomePage/HomePage.tsx
src/pages/HomePage/pages/AssetsManagement/AssetManagement.tsx
src/pages/HomePage/pages/AssetsManagement/pages/ManageAssets.tsx
src/pages/HomePage/pages/EventsManagement/EventsManagement.tsx
src/pages/HomePage/pages/EventsManagement/pages/CreateEvent.tsx
src/pages/HomePage/pages/Members/Members.tsx
src/pages/HomePage/pages/Members/pages/ProfileDetails.tsx
src/pages/HomePage/pages/Requisitions/pages/MyRequests.tsx
src/pages/HomePage/pages/Requisitions/pages/RequestDetails.tsx
src/pages/HomePage/pages/Requisitions/pages/Requisitions.tsx
src/pages/HomePage/pages/Settings/Settings.jsx
src/pages/HomePage/pages/Settings/pages/AccessRights.tsx
src/pages/HomePage/pages/Users/pages/ViewUser.tsx
src/pages/HomePage/store/globalComponentsStore.ts
src/pages/HomePage/utils/helperFunctions.ts

Refactor loader

---

src/components/SearchBar.tsx
src/components/subform/ContactsSubForm.tsx
src/pages/HomePage/Components/Header.tsx
src/pages/HomePage/HomePage.tsx
src/pages/HomePage/pages/AssetsManagement/AssetManagement.tsx
src/pages/HomePage/pages/AssetsManagement/utils/utils.tsx
src/pages/HomePage/pages/EventsManagement/Components/EventsManagerHeader.tsx
src/pages/HomePage/pages/Members/Members.tsx
src/pages/HomePage/pages/Settings/Settings.jsx
src/pages/HomePage/pages/Settings/pages/AccessRights.tsx
src/pages/HomePage/pages/VisitorManagement/Components/VisitorForm.tsx
src/pages/HomePage/pages/VisitorManagement/VisitorManagement.tsx
src/pages/HomePage/pages/VisitorManagement/utils/mapping.ts
src/routes/appRoutes.tsx
src/utils/api/apiPost.ts
src/utils/api/apiPut.ts
src/utils/api/visitors/interfaces.ts
src/utils/helperFunctions.ts
src/utils/interfaces.ts

For testing

---

src/components/MultiSelect.tsx
src/pages/HomePage/pages/LifeCenter/LifeCenter.tsx
src/pages/HomePage/pages/LifeCenter/components/LifeCenterForm.tsx
src/utils/api/apiPost.ts
src/utils/api/apiPut.ts

feat: add and update life center

---

src/pages/HomePage/pages/LifeCenter/components/SoulsWonForm.tsx

feat: add souls-won form

---

src/pages/HomePage/pages/Members/Components/DepartmentPosition.tsx
src/pages/HomePage/pages/Settings/Settings.jsx
src/pages/HomePage/pages/Settings/utils/departmentSlice.ts
src/pages/HomePage/pages/Settings/utils/positionSlice.ts
src/pages/HomePage/pages/Settings/utils/settingsInterfaces.ts

position options

---

src/pages/Registration/Registration.tsx

patched bg changed

---

src/images.d.ts
src/pages/Registration/Registration.tsx
src/pages/Registration/components/Stepper.tsx
src/routes/appRoutes.tsx

complete patch for registration 1.0.2

---

src/pages/HomePage/pages/LifeCenter/components/LifeCenterCard.tsx
src/pages/HomePage/pages/LifeCenter/components/LifeCenterForm.tsx
src/pages/HomePage/pages/LifeCenter/components/SoulsWonForm.tsx

UI Fix on the module form

---

src/pages/HomePage/pages/EventsManagement/utils/eventsSlice.ts
src/pages/HomePage/pages/VisitorManagement/Components/FollowUpForm.tsx
src/pages/HomePage/pages/VisitorManagement/Components/FollowUps.tsx
src/pages/HomePage/pages/VisitorManagement/Components/Visit.tsx
src/pages/HomePage/pages/VisitorManagement/Components/VisitForm.tsx
src/pages/HomePage/pages/VisitorManagement/Components/VisitorForm.tsx

visitor UI Fixes

---

src/pages/HomePage/pages/MarketPlace/components/ProductOverview.tsx
src/pages/HomePage/pages/MarketPlace/components/cards/ProductDetailsCard.tsx

feat: add product overview

---

src/context/AuthWrapper.tsx
src/pages/HomePage/HomePage.tsx
src/routes/ProtectedRoutes.tsx
src/routes/appRoutes.tsx

redirection and clearing of side effect on token expiration

---

src/pages/HomePage/pages/MarketPlace/components/cards/MarketCard.tsx

refactor: market card

---

src/pages/HomePage/pages/MarketPlace/components/ProductDetails.tsx
src/pages/HomePage/pages/MarketPlace/components/cart/CartDrawer.tsx
src/pages/HomePage/pages/MarketPlace/components/cart/CartTable.tsx
src/pages/HomePage/pages/MarketPlace/utils/cartSlice.ts
src/pages/MembersPage/Pages/ViewCart.tsx
src/routes/appRoutes.tsx
src/utils/api/marketPlace/interface.ts
src/utils/const.ts

feat: add cart table

---

src/Wrappers/BackgroundWrapper.tsx

fixed the homepage overflow

---

src/pages/HomePage/pages/MarketPlace/components/ProductDetails.tsx
src/pages/HomePage/pages/MarketPlace/components/cards/ProductCard.tsx
src/pages/HomePage/pages/MarketPlace/components/cart/CartDrawer.tsx
src/pages/HomePage/pages/MarketPlace/components/cart/CartTable.tsx
src/pages/HomePage/pages/MarketPlace/components/cart/CheckOutForm.tsx
src/pages/HomePage/pages/MarketPlace/utils/cartSlice.ts
src/pages/MembersPage/Pages/CheckOutPage.tsx
src/pages/MembersPage/Pages/Market.tsx
src/pages/MembersPage/Pages/MyOrders.tsx
src/pages/MembersPage/Pages/ProductDetailsPage.tsx
src/pages/MembersPage/Pages/ProductsPage.tsx
src/pages/MembersPage/Pages/ViewCart.tsx
src/pages/MembersPage/layouts/MarketLayout.tsx
src/routes/appRoutes.tsx
src/utils/api/marketPlace/interface.ts
src/utils/const.ts

feat: add orders page and refactor market

---

src/components/Modal.tsx
src/pages/HomePage/pages/DashBoard/Components/EventCard.tsx
src/pages/HomePage/pages/DashBoard/Components/UpcomingEvents.tsx
src/pages/MembersPage/MembersPage.tsx
src/utils/api/apiFetch.ts

fixed the Upcoming event

---

src/pages/HomePage/pages/MinistrySchool/Components/TopicAssessment.tsx
src/pages/HomePage/pages/MinistrySchool/pages/ProgramApply.tsx
src/pages/MembersPage/Component/ProgramCard.tsx
src/pages/MembersPage/Component/ProgramDetailsModal.tsx
src/pages/MembersPage/Pages/MyClass.tsx
src/utils/api/ministrySchool/interfaces.ts

fixed the my class page

---

src/pages/HomePage/pages/DashBoard/Components/WelcomeHeader.tsx

changed theme for the year

---

src/index.css
src/pages/HomePage/Components/NavigationLink.tsx
src/pages/HomePage/Components/SidebarSubmenu.tsx
src/pages/HomePage/HomePage.tsx

side nav fix

---

src/pages/HomePage/Components/PageOutline.tsx
src/pages/HomePage/pages/AssetsManagement/AssetManagement.tsx
src/pages/HomePage/pages/EventsManagement/Components/EventForm.tsx
src/pages/HomePage/pages/EventsManagement/EventsManagement.tsx
src/pages/HomePage/pages/EventsManagement/pages/AllEvent.tsx
src/pages/HomePage/pages/LifeCenter/LifeCenter.tsx
src/pages/HomePage/pages/LifeCenter/components/LifeCenterForm.tsx
src/pages/HomePage/pages/LifeCenter/components/LifeCenterMemberForm.tsx
src/pages/HomePage/pages/LifeCenter/components/RolesForm.tsx
src/pages/HomePage/pages/LifeCenter/components/SoulsWonForm.tsx
src/pages/HomePage/pages/LifeCenter/pages/LifeCenterAnalytics.tsx
src/pages/HomePage/pages/LifeCenter/pages/LifeCenterRoles.tsx
src/pages/HomePage/pages/MarketPlace/MarketPlace.tsx
src/pages/HomePage/pages/MarketPlace/components/forms/AddMarketForm.tsx
src/pages/HomePage/pages/MarketPlace/pages/MarketDetail.tsx
src/pages/HomePage/pages/MinistrySchool/MinistrySchool.tsx
src/pages/HomePage/pages/Settings/Settings.tsx
src/pages/HomePage/pages/Settings/pages/AccessRights.tsx
src/pages/HomePage/pages/Settings/pages/ManageAccess.tsx
src/pages/HomePage/pages/Users/UserManagement.tsx
src/pages/HomePage/pages/VisitorManagement/Components/VisitorForm.tsx
src/pages/HomePage/pages/VisitorManagement/VisitorManagement.tsx
src/pages/HomePage/pages/VisitorManagement/pages/VisitorDetails.tsx

modal fixes

---

src/pages/HomePage/pages/MarketPlace/components/ProductDetails.tsx
src/pages/MembersPage/Pages/Market.tsx
src/pages/MembersPage/layouts/MarketLayout.tsx

refactor: market layout

---

src/pages/MembersPage/Pages/CheckOutPage.tsx
src/pages/MembersPage/Pages/VerifyPayment.tsx
src/routes/appRoutes.tsx
src/utils/const.ts

verify payment

---

index.html
src/pages/Authentication/pages/LoginPage/LoginPage.tsx
src/pages/MembersPage/Pages/ProductsPage.tsx

Product page - text change

---

src/pages/HomePage/pages/MarketPlace/components/forms/ProductGallery.tsx
src/pages/HomePage/pages/MarketPlace/pages/AddProduct.tsx

fix: product stock

---

src/pages/HomePage/Components/reusable/ColorSelectField.tsx
src/pages/HomePage/pages/MarketPlace/components/ProductDetails.tsx
src/pages/HomePage/pages/MarketPlace/components/cards/ProductCard.tsx
src/pages/HomePage/pages/MarketPlace/components/cards/ProductDetailsCard.tsx
src/pages/HomePage/pages/MarketPlace/components/cart/CartDrawer.tsx
src/pages/HomePage/pages/MarketPlace/components/cart/CartTable.tsx
src/pages/HomePage/pages/MarketPlace/utils/cartSlice.ts
src/pages/MembersPage/Pages/Market.tsx
src/utils/api/marketPlace/interface.ts

fixes: members-products

---

src/pages/HomePage/pages/MarketPlace/components/ProductDetails.tsx
src/pages/HomePage/pages/MarketPlace/components/cart/CheckOutForm.tsx

fix: padding

---

src/pages/HomePage/Components/reusable/ColorSelectField.tsx
src/pages/HomePage/Components/reusable/Filter.tsx
src/pages/HomePage/pages/MarketPlace/components/Orders/OrderFilters.tsx
src/pages/HomePage/pages/MarketPlace/components/Orders/Orders.tsx
src/pages/HomePage/pages/MarketPlace/components/ProductDetails.tsx
src/pages/HomePage/pages/MarketPlace/components/ProductOverview.tsx
src/pages/HomePage/pages/MarketPlace/components/cart/CheckOutForm.tsx
src/pages/HomePage/pages/MarketPlace/pages/MarketDetail.tsx
src/pages/HomePage/pages/MarketPlace/utils/cartSlice.ts
src/pages/MembersPage/Pages/CheckOutPage.tsx
src/utils/api/marketPlace/interface.ts

fixes: fix ui and checkout flow

---

src/pages/Registration/VisitorRegistration.tsx

featch events for out dir
